### ISSUE TITLE
TypeError: Cannot read property 'font' of undefined

### ISSUE THREAD

**Issue by SunChestnut** [ikeq/hexo-theme-inside#113]
参照你的配置修改了/Blog/_config.yml文件和/Blog/themes/inside/_config.yml文件。powersell内启动hexo后报错如下：（因修改的地方较多，故不一一粘出）

```
PS D:\Blog> hexo server
(node:8120) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 14, column 3:
      background: '//www.toptal.com/de ...
      ^
    at generateError (D:\Blog\\node_modules\\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at storeMappingPair (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:335:7)
    at readBlockMapping (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1098:9)
    at composeNode (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readBlockMapping (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1089:11)
    at composeNode (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (D:\Blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at Hexo.yamlHelper (D:\Blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\Blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\Blog\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:147:5)
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'font' of undefined
    at Hexo.<anonymous> (D:\Blog\themes\inside\lib\config.js:64:26)
    at Hexo.emit (events.js:182:13)
    at Hexo._generate (D:\Blog\node_modules\hexo\lib\hexo\index.js:315:8)
    at loadDatabase.then.then (D:\Blog\node_modules\hexo\lib\hexo\index.js:278:17)
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (D:\Blog\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (D:\Blog\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (D:\Blog\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
感谢你花时间看了我的问题，望回复。

**Comment by ikeq** [comment]
YAMLException: duplicated mapping key at line 14, column 3:
