### ISSUE TITLE
hexo generate error

### ISSUE THREAD

**Issue by OuYanghaoyue** [ikeq/hexo-theme-inside#186]
ReferenceError: /home/haoyue/文档/Web/Temp/themes/inside/layout/index.ejs:6

```
4| <head>
    5|     <meta charset="utf-8">
6|     <title><%= title %></title>
 7|     <base href="<%= config.root %>">
8|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
 9|     <link rel="canonical" href="<%=url_trim
```
(url)%>">

title is not defined
    at eval (/home/haoyue/文档/Web/Temp/themes/inside/layout/index.ejs:13:26)
    at index (/home/haoyue/文档/Web/Temp/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/theme/view.js:41:15)
    at /home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/home/haoyue/文档/Web/Temp/node_modules/bluebird/js/release/util.js:16:23)
    at /home/haoyue/文档/Web/Temp/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:489:10)
    at resume_ (_stream_readable.js:974:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
ERROR /home/haoyue/文档/Web/Temp/themes/inside/layout/index.ejs:6

```
4| <head>
    5|     <meta charset="utf-8">
 >> 6|     <title><%= title %></title>
 >> 7|     <base href="<%= config.root %>">
 >> 8|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
 >> 9|     <link rel="canonical" href="<%=url_trim(url)%>">
```

title is not defined
ReferenceError: /home/haoyue/文档/Web/Temp/themes/inside/layout/index.ejs:6

```
4| <head>
    5|     <meta charset="utf-8">

 >> 6|     <title><%= title %></title>
 >> 7|     <base href="<%= config.root %>">
 >> 8|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
 >> 9|     <link rel="canonical" href="<%=url_trim(u

rl)%>">
```

title is not defined
    at eval (/home/haoyue/文档/Web/Temp/themes/inside/layout/index.ejs:13:26)
    at index (/home/haoyue/文档/Web/Temp/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/theme/view.js:41:15)
    at /home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/home/haoyue/文档/Web/Temp/node_modules/bluebird/js/release/util.js:16:23)
    at /home/haoyue/文档/Web/Temp/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:489:10)
    at resume_ (_stream_readable.js:974:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
INFO  0 files generated in 9.54 ms

我使用别的主题hexo generate 没问题 当切换到你的主题的时候就会报以上错误 麻烦up指导一下 谢谢

**Comment by ikeq** [comment]
刚支持到 hexo@4.2，试试对你这个问题是否也有影响 [2.6.0](https://github.com/ikeq/hexo-theme-inside/releases/tag/2.6.0)

**Comment by OuYanghaoyue** [comment]
谢谢UP 已经可是正常generate了

**Comment by OuYanghaoyue** [comment]
```
/home/haoyue/文档/Web/Temp/themes/inside/lib/config.js:70
    if (theme.appearance.font && theme.appearance.font.url)
                         ^

TypeError: Cannot read property 'font' of undefined
    at Hexo.<anonymous> (/home/haoyue/文档/Web/Temp/themes/inside/lib/config.js:70:26)
    at Hexo.emit (events.js:333:22)
    at Hexo._generate (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/index.js:437:10)
    at Theme.<anonymous> (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/index.js:323:42)
    at Timeout._onTimeout (/home/haoyue/文档/Web/Temp/node_modules/hexo/lib/hexo/index.js:83:28
```
hexo server以后点击链接会出现这个报错 求教UP谢谢

**Comment by OuYanghaoyue** [comment]
我又来了...
关于sidebar menu的
```
menu:
  主页: /
  关于: /about
  搜索: /search
  Github: https://github.com/ikeq3:28
```
按照类似的配置 使用http或者https的按钮不会被渲染成功 用的是2.6.0最新的版本 希望UP指导一下

**Comment by ikeq** [comment]
你的 GitHub 链接后面多了个 3:28

**Comment by OuYanghaoyue** [comment]
经过多次测试,我的config配置如下
```
menu:
  Home: /
  About: /about
  Links: /links
  search: /search
  Img:  https://www.baidu.com
  Resources: /
```


页面效果见https://lossyou.com
hexo generate
无法渲染带有url链接的menu希望UP解决一下谢谢

**Comment by OuYanghaoyue** [comment]
还有bug................ 添加valine的js以后会影响整个hexo页面的样式 伤心

**Comment by fiteen** [comment]
@OuYanghaoyue 可以改造一下 `valine.js`，具体参考我的这篇[博文](https://blog.fiteen.top/2020/hexo-theme-inside-plugin)

**Comment by OuYanghaoyue** [comment]
> @OuYanghaoyue 可以改造一下 `valine.js`，具体参考我的这篇[博文](https://blog.fiteen.top/2020/hexo-theme-inside-plugin)

谢谢 参照你的已经解决了

**Comment by ikeq** [comment]
#191
