### ISSUE TITLE
TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by gaowanliang** [ikeq/hexo-theme-inside#250]
具体代码报错信息
```
TypeError: Cannot read property 'register' of undefined
    at result.plugins.forEach.item (D:\program_data\gaowanliang.github.io\themes\insides\lib\config.js:95:32)
    at Array.forEach (<anonymous>)
    at Hexo.<anonymous> (D:\program_data\gaowanliang.github.io\themes\insides\lib\config.js:76:22)
    at Hexo.emit (events.js:187:15)
    at Hexo._generate (D:\program_data\gaowanliang.github.io\node_modules\_hexo@4.2.1@hexo\lib\hexo\index.js:437:10)
    at loadDatabase.then.then (D:\program_data\gaowanliang.github.io\node_modules\_hexo@4.2.1@hexo\lib\hexo\index.js:310:24)
    at tryCatcher (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (D:\program_data\gaowanliang.github.io\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
```
- 版本：2.7.0-beta.8
- 配置：默认配置，完全没有更改

**Comment by ikeq** [comment]
执行的什么命令，`hexo g` 还是 `hexo serve`?

**Comment by gaowanliang** [comment]
> 执行的什么命令，`hexo g` 还是 `hexo serve`?

`hexo g`

**Comment by ikeq** [comment]
不确定是什么原因，请尝试改一下 themes/insides/lib/config.js，全文替换 `this` 为 `hexo`，然后执行 `hexo clean`，`hexo g`，如果可解决，我会改一下代码。

**Comment by gaowanliang** [comment]
> 不确定是什么原因，请尝试改一下 themes/insides/lib/config.js，全文替换 `this` 为 `hexo`，然后执行 `hexo clean`，`hexo g`，如果可解决，我会改一下代码。

没有效果，报错依旧

**Comment by BluerAngala** [comment]
同问，操作报错

**Comment by BluerAngala** [comment]
![image](https://user-images.githubusercontent.com/49632180/103440451-9ab4d800-4c80-11eb-95ce-949d24fd3f0e.png)


全新项目中引入 inside 主题，hexo  s 运行报错，求解。

**Comment by ikeq** [comment]
@BluerAngala node版本问题吧，升级到最新

**Comment by BluerAngala** [comment]
是的，将node更新到最新之后，问题解决，感谢~

**Comment by Theoshen** [comment]
ERROR Script load failed: themes\inside\scripts\index.js
Error: Cannot find module 'markdown-it'
Require stack:
- D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js
- D:\Blog\myblog\themes\inside\lib\renderer\index.js
- D:\Blog\myblog\themes\inside\scripts\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Blog\myblog\themes\inside\lib\renderer\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:280:23)
    at D:\Blog\myblog\themes\inside\scripts\index.js:2:1
    at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:293:14
    at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'register' of undefined
    at D:\Blog\myblog\themes\inside\lib\config.js:95:32
    at Array.forEach (<anonymous>)
    at Hexo.<anonymous> (D:\Blog\myblog\themes\inside\lib\config.js:76:22)
    at Hexo.emit (events.js:327:22)
    at Hexo._generate (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:437:10)
    at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:310:24
    at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:617:21)
    at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)

node 版本 v14.15.4
执行hexo g  hexo server  都有这些错

**Comment by Theoshen** [comment]
inside版本是2.70-beta.8

**Comment by Theoshen** [comment]
`ERROR Script load failed: themes\inside\scripts\index.js
Error: Cannot find module 'markdown-it'
Require stack:

D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js
D:\Blog\myblog\themes\inside\lib\renderer\index.js
D:\Blog\myblog\themes\inside\scripts\index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js:1:20)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Blog\myblog\themes\inside\lib\renderer\index.js:1:18)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:280:23)
at D:\Blog\myblog\themes\inside\scripts\index.js:2:1
at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:293:14
at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
INFO Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'register' of undefined
at D:\Blog\myblog\themes\inside\lib\config.js:95:32
at Array.forEach ()
at Hexo. (D:\Blog\myblog\themes\inside\lib\config.js:76:22)
at Hexo.emit (events.js:327:22)
at Hexo._generate (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:437:10)
at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:310:24
at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:604:18)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
at PromiseArray._resolve (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:127:19)
at PromiseArray._promiseFulfilled (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:145:14)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:609:26)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:617:21)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
`

node 版本 v14.15.4
inside版本是2.70-beta.8
执行hexo g hexo server 都有这些错

**Comment by Theoshen** [comment]
```
ERROR` Script load failed: themes\inside\scripts\index.js
Error: Cannot find module 'markdown-it'
Require stack:

D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js
D:\Blog\myblog\themes\inside\lib\renderer\index.js
D:\Blog\myblog\themes\inside\scripts\index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Blog\myblog\themes\inside\lib\renderer\markdown\index.js:1:20)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Blog\myblog\themes\inside\lib\renderer\index.js:1:18)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:280:23)
at D:\Blog\myblog\themes\inside\scripts\index.js:2:1
at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:293:14
at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
INFO Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'register' of undefined
at D:\Blog\myblog\themes\inside\lib\config.js:95:32
at Array.forEach ()
at Hexo. (D:\Blog\myblog\themes\inside\lib\config.js:76:22)
at Hexo.emit (events.js:327:22)
at Hexo._generate (D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:437:10)
at D:\Blog\myblog\node_modules\hexo\lib\hexo\index.js:310:24
at tryCatcher (D:\Blog\myblog\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:547:31)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:604:18)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
at PromiseArray._resolve (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:127:19)
at PromiseArray._promiseFulfilled (D:\Blog\myblog\node_modules\bluebird\js\release\promise_array.js:145:14)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:609:26)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
at Promise._settlePromise (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:617:21)
at Promise._settlePromise0 (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (D:\Blog\myblog\node_modules\bluebird\js\release\promise.js:673:18)
```

node 版本 v14.15.4
inside版本是2.70-beta.8
执行hexo g hexo server 都有这些错

**Comment by ikeq** [comment]
@Theoshen 项目根目录执行 `npm install markdown-it markdown-it-container`

**Comment by Theoshen** [comment]
@ikeq 
markdown-it 解决了，但是后面那个问题还在

**Comment by edsion11** [comment]
遇见了相同的问题，执行`hexo clean`后解决了

**Comment by Mao1229** [comment]
> @ikeq markdown-it 解决了，但是后面那个问题还在

hexo -v 检查一下 hexo的版本，版本升级到 7.3.1 即可解决
