### ISSUE TITLE
TypeError: [pages.map(...),helpers.generateHtml(...)].flat is not a function     

### ISSUE THREAD

**Issue by svhero658** [ikeq/hexo-theme-inside#255]
- 运行 `hexo serve` 时报错
- 运行环境 hexo 5.3.0

```
INFO  Start processing                                                                               
FATAL { err:                                                                                         
   TypeError: [pages.map(...),helpers.generateHtml(...)].flat is not a function                      
       at module.exports (/home/ubuntu/blog/themes/inside/lib/generator/entries/pages.js:21:5)       
       at ret.concat.apply.map.item (/home/ubuntu/blog/themes/inside/lib/generator/entries/index.js:1
1:38)                                                                                                
       at Array.map (<anonymous>)
       at Hexo.module.exports (/home/ubuntu/blog/themes/inside/lib/generator/entries/index.js:11:6)
       at generators.map.fn (/home/ubuntu/blog/themes/inside/lib/generator/index.js:25:36)
       at Array.map (<anonymous>)
       at Hexo.<anonymous> (/home/ubuntu/blog/themes/inside/lib/generator/index.js:25:23)
       at Hexo.tryCatcher (/home/ubuntu/blog/node_modules/bluebird/js/release/util.js:16:23)
       at Hexo.<anonymous> (/home/ubuntu/blog/node_modules/bluebird/js/release/method.js:15:34)
       at Promise.map.key (/home/ubuntu/blog/node_modules/hexo/lib/hexo/index.js:405:22)
       at tryCatcher (/home/ubuntu/blog/node_modules/bluebird/js/release/util.js:16:23)
       at MappingPromiseArray._promiseFulfilled (/home/ubuntu/blog/node_modules/bluebird/js/release/m
ap.js:68:38)
       at MappingPromiseArray.PromiseArray._iterate (/home/ubuntu/blog/node_modules/bluebird/js/relea
se/promise_array.js:115:31)
       at MappingPromiseArray.init (/home/ubuntu/blog/node_modules/bluebird/js/release/promise_array.
js:79:10)
       at MappingPromiseArray._asyncInit (/home/ubuntu/blog/node_modules/bluebird/js/release/map.js:3
7:10)
       at _drainQueueStep (/home/ubuntu/blog/node_modules/bluebird/js/release/async.js:97:12)
       at _drainQueue (/home/ubuntu/blog/node_modules/bluebird/js/release/async.js:86:9)
       at Async._drainQueues (/home/ubuntu/blog/node_modules/bluebird/js/release/async.js:102:5)
       at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/blog/node_modules/bluebird/js/r
elease/async.js:15:14)
       at runCallback (timers.js:705:18)
       at tryOnImmediate (timers.js:676:5)
       at processImmediate (timers.js:658:5) } 'Something\'s wrong. Maybe you can find the solution h
ere: %s' '\u001b[4mhttps://hexo.io/docs/troubleshooting.html\u001b[24m'
```

**Comment by ikeq** [comment]
升级 Node 到最新版
