### ISSUE TITLE
npm install和下载到themes解压后hexo s出现错误 

### ISSUE THREAD

**Issue by 0x01x0** [ikeq/hexo-theme-inside#260]
hexo-cli: 4.2.0
os: Linux 4.4.0-19041-Microsoft linux x64
node: 12.20.1
v8: 7.8.279.23-node.45
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 72
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
http_parser: 2.9.4
openssl: 1.1.1i
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0

INFO  Validating config
ERROR {
  err: Error: Cannot find module 'cheerio'
  Require stack:
  - /home/kokin/onegram/node_modules/hexo-theme-inside/lib/config.js
  - /home/kokin/onegram/node_modules/hexo-theme-inside/scripts/index.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
      at Function.Module._load (internal/modules/cjs/loader.js:667:27)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/home/kokin/onegram/node_modules/hexo-theme-inside/lib/config.js:3:17)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at req (/home/kokin/onegram/node_modules/hexo/lib/hexo/index.js:292:23)
      at /home/kokin/onegram/node_modules/hexo-theme-inside/scripts/index.js:1:66
      at /home/kokin/onegram/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/home/kokin/onegram/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/kokin/onegram/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/kokin/onegram/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/kokin/onegram/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/kokin/onegram/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/kokin/onegram/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/kokin/onegram/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/kokin/onegram/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/kokin/onegram/node_modules/bluebird/js/release/async.js:15:14) {        
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/kokin/onegram/node_modules/hexo-theme-inside/lib/config.js',
      '/home/kokin/onegram/node_modules/hexo-theme-inside/scripts/index.js'
    ]
  }
} Script load failed: %s node_modules/hexo-theme-inside/scripts/index.js

**Comment by ikeq** [comment]
npm好久未发布了，可以先手动下载 🤧

**Comment by 0x01x0** [comment]
> npm好久未发布了，可以先手动下载 🤧

我发现是少了组件 cheerio 和 lodash

**Comment by ikeq** [comment]
最新版本不依赖它们了

**Comment by 0x01x0** [comment]
> 最新版本不依赖它们了

但是最新版本我发现缺少的依赖更多了!! 缺少markdown-it之类之类的好多

**Comment by ikeq** [comment]
就两个

**Comment by 0x01x0** [comment]
> 就两个

我先删除hexo重新搞吧 已经被我弄的乱七八糟了 哈哈哈哈
