### ISSUE TITLE
Incompatible with hexo-hide-posts

### ISSUE THREAD

**Issue by DioPong** [ikeq/hexo-theme-inside#285]
I try to hide some articles with `hide: true` in front-matter, but it seems not work. So I tried with hexo plugin hexo-hide-posts but something wrong, here is my log:

```log
FATAL {
  err: TypeError: Cannot read property 'bind' of undefined
      at Hexo.<anonymous> (/home/dio/document/hexos/inside/node_modules/hexo-hide-posts/index.js:74:30)
      at Hexo.tryCatcher (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/method.js:15:34)
      at /home/dio/document/hexos/inside/node_modules/hexo/lib/hexo/index.js:405:22
      at tryCatcher (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/util.js:16:23)
      at MappingPromiseArray._promiseFulfilled (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/map.js:68:38)
      at MappingPromiseArray.PromiseArray._iterate (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/promise_array.js:115:31)
      at MappingPromiseArray.init (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/promise_array.js:79:10)
      at MappingPromiseArray._asyncInit (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/map.js:37:10)
      at _drainQueueStep (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/home/dio/document/hexos/inside/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

I hope this quesion can be fixed, or is there any other method to hide my post?

Thanks!

**Comment by ikeq** [comment]
You can use `layout: false` in front matter to avoid rendering.

**Comment by DioPong** [comment]
Thanks, it works!

**Comment by DioPong** [comment]
Thanks, it work! But seems it can't be visited anymore, what if I just want to hide it? 

With `hexo-hide-posts`, I can just hide it in Home, but post still is still visitable, and it won't be added to sitemap and etc.

**Comment by ikeq** [comment]
#287
